//
// Created by mistlight on 1/27/2017.
//

#ifndef NODOKANATIVE_AUDIOBOOKLISTVIEWHANDLER_H
#define NODOKANATIVE_AUDIOBOOKLISTVIEWHANDLER_H


class AudiobookListViewHandler {

};


#endif //NODOKANATIVE_AUDIOBOOKLISTVIEWHANDLER_H
